# Generated by Django 3.1 on 2021-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('news_type', models.CharField(max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_hackernews', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_date', '-modified_date'],
            },
        ),
    ]
